#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
apiVersion: uniffle.apache.org/v1alpha1
kind: RemoteShuffleService
metadata:
  name: rss-test
  namespace: kube-system
spec:
  configMapName: "rss-configuration"
  coordinator:
    image: "${RSS_SERVER_IMAGE}"
    initContainerImage: "busybox:latest"
    rpcNodePort:
      - 30001
      - 30011
    httpNodePort:
      - 30002
      - 30012
    xmxSize: "800M"
    configDir: "/data/rssadmin/rss/conf"
    replicas: 1
    excludeNodesFilePath: "/data/rssadmin/rss/coo/exclude_nodes"
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    logHostPath: "/data/logs/rss/coordinator"
    hostPathMounts:
      /data/logs/rss/coordinator: /data/rssadmin/rss/logs
  shuffleServer:
    sync: true
    replicas: 1
    image: "${RSS_SERVER_IMAGE}"
    initContainerImage: "busybox:latest"
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
    autoscaler:
      enable: true
      hpaSpec:
        maxReplicas: 3
        metrics:
          - resource:
              name: cpu
              target:
                averageUtilization: 10
                type: Utilization
            type: Resource
    upgradeStrategy:
      type: "FullUpgrade"
    xmxSize: "800M"
    configDir: "/data/rssadmin/rss/conf"
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    logHostPath: "/data/logs/rss/shuffle-server"
    hostPathMounts:
      /data/logs/rss/shuffle-server: /data/rssadmin/rss/logs
      /data/rssdata1: /data1
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rss-configuration
  namespace: kube-system
data:
  coordinator.conf: |-
    rss.coordinator.app.expired 60000
    rss.coordinator.exclude.nodes.file.path /data/rssadmin/rss/coo
    rss.coordinator.server.heartbeat.timeout 30000
    rss.jetty.http.port 19996
    rss.rpc.server.port 19997
  log4j.properties: |-
    log4j.rootCategory=INFO, RollingAppender
    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.Threshold=INFO
    log4j.appender.console.target=System.err
    log4j.appender.console.layout=org.apache.log4j.PatternLayout
    log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n
    log4j.appender.RollingAppender=org.apache.log4j.RollingFileAppender
    log4j.appender.RollingAppender.File=./logs/rss.log
    log4j.appender.RollingAppender.MaxFileSize=50MB
    log4j.appender.RollingAppender.MaxBackupIndex=10
    log4j.appender.RollingAppender.layout=org.apache.log4j.PatternLayout
    log4j.appender.RollingAppender.layout.ConversionPattern=[%p] %d %t %c{1} %M - %m%n
  server.conf: |-
    rss.coordinator.quorum rss-coordinator-rss-demo-0:19997,rss-coordinator-rss-demo-1:19997
    rss.jetty.http.port 19996
    rss.server.buffer.capacity 335544320
    rss.server.read.buffer.capacity 167772160
    rss.storage.type MEMORY_LOCALFILE
